# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: garden.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from . import types_pb2 as types__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0cgarden.proto\x1a\x0btypes.proto2\x97\x01\n\x07Gardens\x12G\n\x0c\x43reateGarden\x12\x1b.garden.CreateGardenRequest\x1a\x1a.garden.CreateGardenResult\x12\x43\n\nGetGardens\x12\x19.garden.GetGardensRequest\x1a\x18.garden.GetGardensResult0\x01\x62\x06proto3')



_GARDENS = DESCRIPTOR.services_by_name['Gardens']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _GARDENS._serialized_start=30
  _GARDENS._serialized_end=181
# @@protoc_insertion_point(module_scope)
