# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: types.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0btypes.proto\x12\x06garden\"8\n\x06Garden\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\r\n\x05place\x18\x02 \x01(\t\x12\x11\n\tgarden_id\x18\x03 \x01(\r\"2\n\x13\x43reateGardenRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\r\n\x05place\x18\x02 \x01(\t\"4\n\x12\x43reateGardenResult\x12\x1e\n\x06garden\x18\x01 \x01(\x0b\x32\x0e.garden.Garden\"!\n\x11GetGardensRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\"2\n\x10GetGardensResult\x12\x1e\n\x06garden\x18\x01 \x01(\x0b\x32\x0e.garden.Gardenb\x06proto3')



_GARDEN = DESCRIPTOR.message_types_by_name['Garden']
_CREATEGARDENREQUEST = DESCRIPTOR.message_types_by_name['CreateGardenRequest']
_CREATEGARDENRESULT = DESCRIPTOR.message_types_by_name['CreateGardenResult']
_GETGARDENSREQUEST = DESCRIPTOR.message_types_by_name['GetGardensRequest']
_GETGARDENSRESULT = DESCRIPTOR.message_types_by_name['GetGardensResult']
Garden = _reflection.GeneratedProtocolMessageType('Garden', (_message.Message,), {
  'DESCRIPTOR' : _GARDEN,
  '__module__' : 'types_pb2'
  # @@protoc_insertion_point(class_scope:garden.Garden)
  })
_sym_db.RegisterMessage(Garden)

CreateGardenRequest = _reflection.GeneratedProtocolMessageType('CreateGardenRequest', (_message.Message,), {
  'DESCRIPTOR' : _CREATEGARDENREQUEST,
  '__module__' : 'types_pb2'
  # @@protoc_insertion_point(class_scope:garden.CreateGardenRequest)
  })
_sym_db.RegisterMessage(CreateGardenRequest)

CreateGardenResult = _reflection.GeneratedProtocolMessageType('CreateGardenResult', (_message.Message,), {
  'DESCRIPTOR' : _CREATEGARDENRESULT,
  '__module__' : 'types_pb2'
  # @@protoc_insertion_point(class_scope:garden.CreateGardenResult)
  })
_sym_db.RegisterMessage(CreateGardenResult)

GetGardensRequest = _reflection.GeneratedProtocolMessageType('GetGardensRequest', (_message.Message,), {
  'DESCRIPTOR' : _GETGARDENSREQUEST,
  '__module__' : 'types_pb2'
  # @@protoc_insertion_point(class_scope:garden.GetGardensRequest)
  })
_sym_db.RegisterMessage(GetGardensRequest)

GetGardensResult = _reflection.GeneratedProtocolMessageType('GetGardensResult', (_message.Message,), {
  'DESCRIPTOR' : _GETGARDENSRESULT,
  '__module__' : 'types_pb2'
  # @@protoc_insertion_point(class_scope:garden.GetGardensResult)
  })
_sym_db.RegisterMessage(GetGardensResult)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _GARDEN._serialized_start=23
  _GARDEN._serialized_end=79
  _CREATEGARDENREQUEST._serialized_start=81
  _CREATEGARDENREQUEST._serialized_end=131
  _CREATEGARDENRESULT._serialized_start=133
  _CREATEGARDENRESULT._serialized_end=185
  _GETGARDENSREQUEST._serialized_start=187
  _GETGARDENSREQUEST._serialized_end=220
  _GETGARDENSRESULT._serialized_start=222
  _GETGARDENSRESULT._serialized_end=272
# @@protoc_insertion_point(module_scope)
